export const REVIEWS_FETCH_REQUEST = 'REVIEWS_FETCH_REQUEST'
export const REVIEWS_FETCH_SUCCESS = 'REVIEWS_FETCH_SUCCESS'
export const REVIEWS_FETCH_FAILURE = 'REVIEWS_FETCH_FAILURE'
export const CRITICS_FETCH_REQUEST = 'CRITICS_FETCH_REQUEST'
export const CRITICS_FETCH_SUCCESS = 'CRITICS_FETCH_SUCCESS'
export const CRITICS_FETCH_FAILURE = 'CRITICS_FETCH_FAILURE'


export const getMovieReviews = () => ({
  type: REVIEWS_FETCH_REQUEST
});

export const getCritics = () => ({
  type: CRITICS_FETCH_REQUEST
});